export const CHAPTER_INTERLUDES = Object.freeze([
  {
    id: "northstar",
    order: 1,
    chapter: "Chapter 1",
    title: "Follow Northstar",
    eligibleWhen: { type: "path", path: "progress.prologueComplete", equals: true },
    beats: [
      { kind: "transition", label: "After midnight", title: "A name survives the fire", image: "./assets/scenes/home-office.webp", text: "Vale is gone. The false renovation is no longer a small corruption story; it is the trail he built for whoever came looking." },
      { kind: "montage", label: "The Ledger morgue", title: "Northstar Civic Works", image: "./assets/scenes/newsroom.webp", text: "One shell contractor appears in old invoices, canceled permits, and relief bids. Every address resolves to 1400 Harrow Street." },
      { kind: "chapter", label: "Greyhaven · 06:12", title: "The office that is not there", image: "./assets/scenes/northstar-harrow.webp", text: "Morning finds you beneath a brass directory that stops at Suite 409. Northstar claims Suite 410." },
    ],
  },
  {
    id: "foundation",
    order: 2,
    chapter: "Chapter 2",
    title: "The Foundation",
    eligibleWhen: { type: "flag", key: "northstarRoutesToBrighterHorizon" },
    beats: [
      { kind: "transition", label: "Courier route confirmed", title: "Someone receives the mail", image: "./assets/scenes/northstar-harrow.webp", text: "Northstar has no office, no staff, and no furniture. Its envelopes still reach Brighter Horizon every Thursday." },
      { kind: "intercept", label: "Recovered voicemail · 00:09", title: "Keep the contractor invisible", image: "./assets/scenes/brighter-horizon-office.webp", speaker: "Unknown administrator", text: "Do not place Northstar on the public ledger. Route it through program advances and keep E. Marsh on the door." },
      { kind: "chapter", label: "Calder Square", title: "Charity in polished glass", image: "./assets/scenes/brighter-horizon-office.webp", text: "The foundation calls itself a bridge between wealth and human need. The courier manifest calls it Northstar's front door." },
    ],
  },
  {
    id: "pattern",
    order: 3,
    chapter: "Chapter 3",
    title: "The Pattern",
    eligibleWhen: { type: "flag", key: "mappedContinuitySiteNetwork" },
    beats: [
      { kind: "montage", label: "Register 09", title: "The same names, every disaster", image: "./assets/scenes/municipal-archive.webp", text: "A charity ledger overlays a municipal emergency map. The shell companies do not respond to crises. They arrive before them." },
      { kind: "intercept", label: "Archive desk line · traced", title: "Destroy the second ledger", image: "./assets/scenes/municipal-archive.webp", speaker: "Meridian compliance", text: "Pull the continuity registers before morning. If Harcourt copied anything, move Bellwether to active containment." },
      { kind: "chapter", label: "Bellwether district", title: "A crisis waiting to happen", image: "./assets/scenes/bellwether-relief-station.webp", text: "Relief crates stand ready beside taps that have not failed yet. Greyhaven's poorest neighborhood is about to become a demonstration." },
    ],
  },
  {
    id: "redoubt",
    order: 4,
    chapter: "Chapter 4",
    title: "Redoubt",
    eligibleWhen: { type: "flag", key: "provedCrownlineGovernanceModel" },
    beats: [
      { kind: "transition", label: "Crownline model recovered", title: "The dashboard chooses winners", image: "./assets/scenes/crownline-data-center.webp", text: "Crownline scores suffering, predicts political surrender, and reserves transport for the people financing the collapse." },
      { kind: "intercept", label: "Encrypted dispatch · Hangar 4", title: "Protected assets moving", image: "./assets/scenes/greyhaven-executive-airfield.webp", speaker: "Redoubt operations", text: "Priority passengers depart before the Bellwether story breaks. Destination remains Orpheus. No names on the civilian manifest." },
      { kind: "chapter", label: "Executive airfield · 04:40", title: "Catch the architects before they fly", image: "./assets/scenes/greyhaven-executive-airfield.webp", text: "Rain closes over a private runway. The Benefactors are already boarding." },
    ],
  },
  {
    id: "orpheus",
    order: 5,
    chapter: "Chapter 5",
    title: "Orpheus",
    eligibleWhen: { type: "flag", key: "provedRedoubtEvacuation" },
    beats: [
      { kind: "montage", label: "Flight path reconstructed", title: "An island outside the map", image: "./assets/scenes/greyhaven-executive-airfield.webp", text: "Redoubt's passengers vanish from public airspace. A maintenance strip continues over black water to Site Orpheus." },
      { kind: "intercept", label: "Harbor channel 3", title: "Cold chain has priority", image: "./assets/scenes/blackwater-point.webp", speaker: "Unregistered launch", text: "Hold the medical cargo below deck. Benefactor transfer comes first. Window 04 opens on the tide." },
      { kind: "chapter", label: "Blackwater Point", title: "Find the island's hidden lifeline", image: "./assets/scenes/blackwater-point.webp", text: "A maintenance pier supplies a destination the harbor authority insists does not exist." },
    ],
  },
  {
    id: "island",
    order: 6,
    chapter: "Chapter 6",
    title: "The Island",
    eligibleWhen: { type: "flag", key: "provedOrpheusSupplyRoute" },
    beats: [
      { kind: "transition", label: "Window 04", title: "Nineteen minutes offshore", image: "./assets/scenes/blackwater-point.webp", text: "A borrowed maintenance badge, a refrigerated launch, and a tide window carry you beyond Greyhaven's lights." },
      { kind: "montage", label: "North Reef", title: "The harbor beneath paradise", image: "./assets/scenes/orpheus-sublevel-harbor.webp", text: "Above: a private conservation retreat. Below: a clinic, an armory, an evacuation registry, and elevators climbing seven secured levels." },
      { kind: "chapter", label: "Site Orpheus · Sublevel", title: "The people upstairs", image: "./assets/scenes/orpheus-sublevel-harbor.webp", text: "The island was not built to hide from catastrophe. It was built for the people who manufacture it." },
    ],
  },
  {
    id: "first-circle",
    order: 7,
    chapter: "Chapter 7",
    title: "The First Circle",
    eligibleWhen: { type: "flag", key: "provedOrpheusCommandCenter" },
    beats: [
      { kind: "transition", label: "Freight elevator · Level 07", title: "The owners are in session", image: "./assets/scenes/orpheus-sublevel-harbor.webp", text: "The service elevator opens behind an assembly hall. No masks. No aliases. They have never needed them here." },
      { kind: "intercept", label: "Live floor microphone", title: "Motion: Port Prosper", image: "./assets/scenes/orpheus-first-circle.webp", speaker: "First Circle chair", text: "Authorize conversion. Water instability at thirty-six hours; grid event at forty-eight. Relief acquisition follows public surrender." },
      { kind: "chapter", label: "Vote in progress", title: "Record everything", image: "./assets/scenes/orpheus-first-circle.webp", text: "One recorder can turn a private vote into evidence. One mistake can leave it buried with you." },
    ],
  },
  {
    id: "consequences",
    order: 8,
    chapter: "Chapter 8",
    title: "Consequences",
    eligibleWhen: { type: "flag", key: "portProsperDecisionMade" },
    beats: [
      { kind: "transition", label: "The choice leaves your hands", title: "Forty-eight hours becomes forty-one", image: "./assets/scenes/home-office.webp", variants: { warn: "Trusted crews quietly isolate the systems named in the portfolio. Meridian still believes its secret is safe.", publish: "The First Circle recording races across mirrors worldwide. Meridian begins burning every exposed route.", stay: "You keep the disguise and climb toward the residential wing while Port Prosper's clock continues running." } },
      { kind: "intercept", label: "Secure service channel", title: "Aster House, respond", image: "./assets/scenes/aster-house.webp", speaker: "Meridian control", text: "Maintain the trigger schedule. Purge the support ledger. If Port Prosper hardens early, activate Relay 7." },
      { kind: "chapter", label: "11 Aldermere Row", title: "The hand on the switch", image: "./assets/scenes/aster-house.webp", text: "The global conspiracy has a local address: a quiet Greyhaven townhouse with its lights on after midnight." },
    ],
  },
  {
    id: "trigger-cell",
    order: 9,
    chapter: "Chapter 9",
    title: "The Trigger Cell",
    eligibleWhen: { type: "flag", key: "identifiedAsterHouse" },
    beats: [
      { kind: "transition", label: "Aster trace authenticated", title: "The attack is already rehearsed", image: "./assets/scenes/aster-house.webp", text: "Aster House has operators, target clocks, city credentials, and the authority to turn a forecast into a catastrophe." },
      { kind: "intercept", label: "Switchboard echo · 02:04", title: "Relay 7 standing by", image: "./assets/scenes/aster-house.webp", speaker: "Unknown operator", text: "Port Prosper rejected the primary keys. Ghost relay opens at 02:10. Six minutes of darkness will be enough." },
      { kind: "chapter", label: "Six minutes", title: "Build the countermeasure", image: "./assets/scenes/port-prosper-signal-exchange.webp", text: "Proof is no longer enough. The evidence must reach Port Prosper before the trigger does." },
    ],
  },
  {
    id: "archipelago",
    order: 10,
    chapter: "Chapter 10",
    title: "The Archipelago Protocol",
    eligibleWhen: { type: "flag", key: "provedAsterHouseTriggerCell" },
    beats: [
      { kind: "montage", label: "Countermeasure packet delivered", title: "A city survives the night", image: "./assets/scenes/port-prosper-signal-exchange.webp", text: "Water keeps moving. Hospital lights remain on. The ghost relay opens, copies its orders, and dies before it can finish the attack." },
      { kind: "intercept", label: "Intercepted retaliation call", title: "Invoke Archipelago", image: "./assets/scenes/port-prosper-signal-exchange.webp", speaker: "Silas Wren", text: "Orpheus is exposed. Move Shepherd's archive to Vesper Key. Trace the newsroom cipher and close every sanctuary route behind it." },
      { kind: "chapter", label: "05:30 · Eastern terminal", title: "Seven islands", image: "./assets/scenes/port-prosper-signal-exchange.webp", text: "The secret island was never the secret. It was one node in a chain—and a courier is carrying the map to the next one." },
    ],
  },
]);
