export const EVIDENCE = Object.freeze({
  email_meridian: {
    id: "email_meridian",
    title: "Anonymous email",
    category: "document",
    summary: "A tip alleging Mayor Vale diverted accessibility funds.",
    artifact: {
      type: "email",
      from: "undisclosed",
      to: "investigations@greyhavenledger.test",
      sent: "Tuesday · 9:41 PM",
      subject: "(no subject)",
      paragraphs: [
        "Mayor Vale diverted accessibility funds to build a private west wing.",
        "The city paid Northstar Construction. Northstar does not exist.",
        "Ask why the west wing must be ready before the Meridian guests arrive.",
        "Start with the invoice.",
      ],
      highlightedPhrase: "Meridian guests",
    },
  },
  invoice_northstar: {
    id: "invoice_northstar",
    title: "Northstar invoice",
    category: "document",
    summary: "$184,600 billed to the municipal accessibility fund.",
    artifact: {
      type: "invoice",
      invoiceNumber: "NS-8841",
      vendor: "NORTHSTAR CONSTRUCTION GROUP",
      vendorAddress: "1400 Harrow Street, Suite 410 · Greyhaven",
      billedTo: "City of Greyhaven · Municipal Accessibility Fund",
      project: "Vale Residence — West Wing Accessibility Improvement",
      issueDate: "March 14",
      dueDate: "PAID · March 17",
      lineItems: [
        ["Structural excavation and reinforcement", "$62,400.00"],
        ["Electrical and shielded communications conduit", "$47,800.00"],
        ["Acoustic isolation materials", "$28,900.00"],
        ["Secure access hardware", "$31,500.00"],
        ["Site restoration and administrative fee", "$14,000.00"],
      ],
      total: "$184,600.00",
      account: "ACCESS-IMPROVEMENT / 44-018",
      authorization: "E. VALE",
      footer: "Payment remitted to Northstar Holdings Clearing Account 7719.",
    },
  },
  permit_summary: {
    id: "permit_summary",
    title: "West-wing permit summary",
    category: "document",
    summary: "A public permit summary for an addition to Mayor Vale’s home.",
    artifact: {
      type: "permit",
      permitNumber: "18-441-W",
      status: "APPROVED — REVISION PENDING",
      address: "17 Bellweather Lane, Greyhaven",
      applicant: "Office of Mayor Evelyn Vale",
      contractor: "Northstar Construction Group",
      scope: "West-wing accessibility improvement and residential lift access.",
      filed: "March 12 · 4:16 PM",
      revised: "March 18 · 12:43 AM",
      inspection: "March 17 · 10:20 AM",
      warning:
        "Amendment history restricted. Submit Form 17-C to the Records Division.",
    },
  },
  permit_amendment_note: {
    id: "permit_amendment_note",
    title: "Permit amendment note",
    category: "document",
    summary: "An amendment authorized after midnight by someone identified as E. Marsh.",
    artifact: {
      type: "memo",
      heading: "RECORDS TERMINAL — HANDWRITTEN NOTE",
      body: [
        "Permit 18-441-W amended after inspection.",
        "Emergency authorization token: E. MARSH",
        "Timestamp: 12:43 AM",
        "Lionel insists the change came after the inspection, not before.",
      ],
      handwritten: "You did not hear this from me. — L.P.",
    },
  },
  june_statement: {
    id: "june_statement",
    title: "June Bell’s statement",
    category: "recording",
    summary: "Deliveries arrived at night, but no above-ground construction followed.",
    artifact: {
      type: "transcript",
      heading: "RECORDED STATEMENT — JUNE BELL",
      timestamp: "4:31 PM · Bellweather Lane",
      lines: [
        ["ROWAN", "How many deliveries did you see?"],
        ["JUNE BELL", "Three trucks after midnight. Men carried equipment through the side gate."],
        ["ROWAN", "And the west-wing construction?"],
        ["JUNE BELL", "There was none. I would have noticed a room appearing."],
        ["JUNE BELL", "I felt drilling through my floorboards, though. It came from below."],
      ],
    },
  },
  photo_west_wall: {
    id: "photo_west_wall",
    title: "Photograph of Vale’s west wall",
    category: "photograph",
    summary: "The original brickwork and roofline are intact. No west wing was built.",
    artifact: {
      type: "photo",
      caption: "WEST ELEVATION · 17 BELLWEATHER LANE · 4:26 PM",
      annotations: [
        "Original 1912 brickwork remains uninterrupted",
        "No new roofline, foundation, or exterior access",
        "Heavy tire marks terminate beside the side gate",
      ],
    },
  },
  study_floorplan: {
    id: "study_floorplan",
    title: "Original Vale house floorplan",
    category: "document",
    summary: "An older plan marks dead space behind the study’s western bookcase.",
    artifact: {
      type: "floorplan",
      heading: "VALE RESIDENCE — ORIGINAL GROUND FLOOR",
      revision: "Survey copy · September 1912",
      rooms: ["STUDY", "HALL", "PARLOR", "SERVICE STAIR", "WESTERN VOID"],
      note: "The current study bookcase sits 31 inches forward of the wall shown here.",
    },
  },
  vale_damaged_recording: {
    id: "vale_damaged_recording",
    title: "Mayor Vale’s damaged recorder",
    category: "recording",
    summary: "Three recovered fragments have lost their timestamps.",
    artifact: {
      type: "recording",
      heading: "E. VALE — DICTATION RECORDER",
      duration: "00:47 recovered",
      fragments: [
        "Fragment A — timestamp unreadable",
        "Fragment B — timestamp unreadable",
        "Fragment C — timestamp unreadable",
      ],
      background: ["three ambient markers detected", "sequence unavailable"],
    },
  },
  vale_reconstructed_message: {
    id: "vale_reconstructed_message",
    title: "Vale’s reconstructed message",
    category: "recording",
    summary:
      "Vale made the irregular invoice conspicuous and named Meridian as the reason.",
    artifact: {
      type: "recording",
      heading: "E. VALE — RECOVERED MESSAGE",
      duration: "00:47 continuous",
      fragments: [
        "If someone found the invoice, then the irregularity worked. I needed the payment to look wrong.",
        "Not a west wing. Beneath it. Meridian arrives Thursday.",
        "Do not trust the guest list. The names are the invitation, not the guests. Follow Northstar. If I am gone, I did not run.",
      ],
      background: ["midnight chime", "freight train", "steady rain"],
    },
  },
  meridian_guest_list_header: {
    id: "meridian_guest_list_header",
    title: "Meridian guest-list header",
    category: "document",
    summary:
      "A torn printout confirms a Meridian session beneath the Vale residence.",
    artifact: {
      type: "memo",
      heading: "MERIDIAN / GREYHAVEN SESSION",
      body: [
        "THURSDAY · 21:00",
        "HOST SITE: VALE / ROOM B",
        "ATTENDEES: [PAGE TORN]",
        "PRINT QUEUE SOURCE: TERMINAL 06",
        "RECOVERY STATUS: HEADER ONLY",
      ],
      handwritten: "Only the header survived in the printer tray.",
    },
  },
  northstar_address: {
    id: "northstar_address",
    title: "Northstar registered address",
    category: "location",
    summary: "1400 Harrow Street, Suite 410 — the next lead in Greyhaven.",
    artifact: {
      type: "memo",
      heading: "NEXT LEAD — NORTHSTAR CONSTRUCTION",
      body: [
        "1400 HARROW STREET · SUITE 410",
        "The address appears on Northstar invoice NS-8841.",
        "Vale’s reconstructed message says to follow Northstar.",
      ],
      handwritten: "Find out who collects the mail.",
    },
  },
  meridian_gala_photograph: {
    id: "meridian_gala_photograph",
    title: "Circled gala photograph",
    category: "photograph",
    summary:
      "A Brighter Horizon gala photograph delivered anonymously, with one face circled.",
    artifact: {
      type: "photo",
      image: "./assets/evidence/gala-photograph.webp",
      alt:
        "A formal humanitarian gala group photograph. A watchful man at the right edge is circled in dark red.",
      caption: "BRIGHTER HORIZON WINTER BENEFIT · PRESS PHOTOGRAPH",
      annotations: [
        "CASSIAN ROOK — founder, centered beneath the donor wall",
        "MAYOR EVELYN VALE — identified near the edge of the original print",
        "UNKNOWN MAN — circled after the photograph was printed",
        "Reverse: 1400 HARROW STREET",
      ],
    },
  },
});

export const INVENTORY_ITEMS = Object.freeze({
  press_credentials: { id: "press_credentials", name: "Press credentials", icon: "ID" },
  smartphone: { id: "smartphone", name: "Phone & camera", icon: "CAM" },
  recorder: { id: "recorder", name: "Audio recorder", icon: "REC" },
  notebook: { id: "notebook", name: "Reporter’s notebook", icon: "NOTE" },
});

export const DIALOGUES = Object.freeze({
  lionel_records: {
    id: "lionel_records",
    character: "Lionel Price",
    portrait: "LP",
    portraitAsset: "./assets/scenes/lionel-price.webp",
    start: "intro",
    nodes: {
      intro: {
        id: "intro",
        speaker: "Lionel Price",
        text: "Everything available to the public is in the summary. If it is not in the summary, it is not available.",
        choices: [
          {
            id: "ask-amendment",
            text: "Who filed the amendment?",
            next: "denial",
          },
          {
            id: "show-invoice",
            text: "Then explain this Northstar invoice.",
            evidenceId: "invoice_northstar",
            requires: { type: "hasEvidence", id: "invoice_northstar" },
            next: "invoice",
          },
          { id: "leave", text: "That’s all for now.", end: true },
        ],
      },
      denial: {
        id: "denial",
        speaker: "Lionel Price",
        text: "There was no amendment. You are mistaking a system timestamp for a filing.",
        choices: [
          {
            id: "show-permit",
            text: "The public summary says ‘revision pending.’",
            evidenceId: "permit_summary",
            requires: { type: "hasEvidence", id: "permit_summary" },
            effects: [
              { type: "setFlag", key: "caughtLionelContradiction", value: true },
            ],
            next: "defensive",
          },
          { id: "ask-system", text: "Who can access the system after hours?", next: "system" },
          { id: "leave", text: "I’ll come back with the paperwork.", end: true },
        ],
      },
      invoice: {
        id: "invoice",
        speaker: "Lionel Price",
        text: "Northstar is a registered vendor. Or it was when the payment cleared. Vendor status is Finance, not Records.",
        choices: [
          { id: "press", text: "You checked after I arrived, didn’t you?", next: "defensive" },
          { id: "back", text: "Let’s start again.", next: "intro" },
        ],
      },
      system: {
        id: "system",
        speaker: "Lionel Price",
        text: "The mayor, the deputy clerk, Information Services, and anyone with an emergency authorization token.",
        choices: [
          { id: "ask-token", text: "Who used an emergency token?", next: "defensive" },
          { id: "back", text: "Back up.", next: "denial" },
        ],
      },
      defensive: {
        id: "defensive",
        speaker: "Lionel Price",
        text: "I did not authorize it. The log says E. Marsh, 12:43 AM. That is all I know—and you did not hear it from me.",
        onEnter: [
          { type: "setFlag", key: "lionelNamedMarsh", value: true },
          { type: "collectEvidence", id: "permit_amendment_note" },
        ],
        choices: [
          { id: "protect", text: "I’ll keep your name out of it.", next: "protected" },
          { id: "challenge", text: "You should have reported this.", next: "resentful" },
        ],
      },
      protected: {
        id: "protected",
        speaker: "Lionel Price",
        text: "Then write this down: the change came after the inspection, not before. That is not how permits work.",
        choices: [{ id: "finish", text: "Thank you, Lionel.", end: true }],
      },
      resentful: {
        id: "resentful",
        speaker: "Lionel Price",
        text: "To whom? The mayor? The deputy clerk? You still think the forms protect the people who file them.",
        choices: [{ id: "finish", text: "I have what I need.", end: true }],
      },
    },
  },
  june_window: {
    id: "june_window",
    character: "June Bell",
    portrait: "JB",
    portraitAsset: "./assets/scenes/june-bell.webp",
    start: "intro",
    nodes: {
      intro: {
        id: "intro",
        speaker: "June Bell",
        text: "If you’re selling something, I’m eighty years old and already own too much of everything.",
        choices: [
          { id: "press", text: "I’m with the Greyhaven Ledger.", next: "journalist" },
          { id: "direct", text: "Did you see construction at Mayor Vale’s house?", next: "construction" },
          { id: "leave", text: "Sorry to bother you.", end: true },
        ],
      },
      journalist: {
        id: "journalist",
        speaker: "June Bell",
        text: "A journalist? The last one who came here wanted a photograph of Evelyn planting tulips.",
        choices: [
          { id: "ask-delivery", text: "I’m interested in the nighttime deliveries.", next: "construction" },
          { id: "leave", text: "I may come back.", end: true },
        ],
      },
      construction: {
        id: "construction",
        speaker: "June Bell",
        text: "Three trucks after midnight. Men carried equipment through the side gate. But nobody built a west wing. I would have noticed a room appearing.",
        onEnter: [
          { type: "setFlag", key: "juneSawDeliveries", value: true },
          { type: "collectEvidence", id: "june_statement" },
        ],
        choices: [
          { id: "ask-sound", text: "What did you hear?", next: "sound" },
          { id: "ask-men", text: "Could you identify the workers?", next: "workers" },
        ],
      },
      sound: {
        id: "sound",
        speaker: "June Bell",
        text: "A low vibration. Not hammering—more like drilling, except it came up through the floorboards.",
        choices: [{ id: "finish", text: "May I quote you?", end: true }],
      },
      workers: {
        id: "workers",
        speaker: "June Bell",
        text: "No uniforms. One van had a compass-star logo. I sketched it because I did not trust my memory.",
        choices: [{ id: "finish", text: "I’d like to see that sketch later.", end: true }],
      },
    },
  },
});

export const DEDUCTIONS = Object.freeze({
  northstar_payment: {
    id: "northstar_payment",
    title: "The payment and permit describe the same job",
    journalText:
      "The city permit and Northstar’s invoice point to the same west-wing project—but Northstar’s existence is still unverified.",
    requiredEvidence: ["invoice_northstar", "permit_summary"],
    requiredConnections: [
      {
        a: "invoice_northstar",
        b: "permit_summary",
        type: "financial",
      },
    ],
    effects: [
      { type: "setFlag", key: "connectedInvoiceToPermit", value: true },
    ],
  },
  witness_contradiction: {
    id: "witness_contradiction",
    title: "The declared construction never happened",
    journalText:
      "June saw equipment delivered, but no west wing was built. The money purchased something hidden at the property.",
    notification:
      "Mayor Vale has disappeared. Her study is now available on the map.",
    requiredEvidence: ["permit_summary", "june_statement", "photo_west_wall"],
    requiredConnections: [
      {
        a: "permit_summary",
        b: "june_statement",
        type: "contradiction",
      },
      {
        a: "permit_summary",
        b: "photo_west_wall",
        type: "contradiction",
      },
    ],
    effects: [
      { type: "setFlag", key: "suspectsHiddenConstruction", value: true },
      { type: "setFlag", key: "mayorMissing", value: true },
      { type: "setPath", path: "progress.officeState", value: 1 },
      { type: "unlockLocation", id: "mayor_study" },
    ],
  },
  vale_distress_signal: {
    id: "vale_distress_signal",
    title: "The irregularity was Vale’s distress signal",
    journalText:
      "The false renovation was not a private luxury. Vale made the payment conspicuous so someone outside Meridian would find the room and follow Northstar.",
    notification:
      "Vale meant the invoice to be found. Three knocks sound at the door.",
    requiredDeductions: ["witness_contradiction"],
    requiredEvidence: [
      "invoice_northstar",
      "photo_west_wall",
      "email_meridian",
      "vale_reconstructed_message",
    ],
    requiredConnections: [
      {
        a: "invoice_northstar",
        b: "photo_west_wall",
        type: "contradiction",
      },
      {
        a: "email_meridian",
        b: "vale_reconstructed_message",
        type: "confirmed",
      },
    ],
    effects: [
      { type: "setFlag", key: "confirmedMeridianLead", value: true },
      { type: "setFlag", key: "prologueEndingReady", value: true },
      { type: "setPath", path: "progress.officeState", value: 2 },
    ],
  },
});

export const GAME_CONTENT = Object.freeze({
  title: "The Benefactors",
  subtitle: "Every good lie leaves paperwork.",
  chapter: "Prologue · The Renovation",
  locations: {
    home_office: {
      id: "home_office",
      name: "Home Office",
      mapX: 51,
      mapY: 62,
      description: "Your apartment and the center of the investigation.",
    },
    ledger_newsroom: {
      id: "ledger_newsroom",
      name: "The Greyhaven Ledger",
      eyebrow: "Tomorrow's news, yesterday's computers",
      mapX: 34,
      mapY: 40,
      description:
        "The night desk glows beneath tired fluorescent lights. Mara is waiting with an assignment that should be simple.",
      sceneClass: "scene-newsroom",
      sceneArt: "./assets/scenes/newsroom.webp",
      hotspots: [
        {
          id: "mara-desk",
          label: "Mara Venn",
          x: 67,
          y: 27,
          width: 18,
          height: 47,
          title: "Mara’s desk",
          text: "Your editor has gone home. Her coffee has not.",
        },
        {
          id: "deadline-clock",
          label: "Deadline clock",
          x: 78,
          y: 8,
          width: 12,
          height: 13,
          title: "9:32 PM",
          text: "The clock is four minutes fast. Mara calls that optimism.",
        },
        {
          id: "archive-boxes",
          label: "Archive boxes",
          x: 5,
          y: 51,
          width: 27,
          height: 31,
          title: "Municipal archive",
          text: "Last year’s council minutes. Useful if the city ever starts repeating itself.",
        },
      ],
    },
    city_hall: {
      id: "city_hall",
      name: "Greyhaven City Hall",
      eyebrow: "Records Division · 10:06 AM",
      mapX: 57,
      mapY: 35,
      description:
        "Marble, fluorescent light, and the institutional confidence that no one reads the forms.",
      sceneClass: "scene-city-hall",
      sceneArt: "./assets/scenes/city-hall.webp",
      hotspots: [
        {
          id: "records-terminal",
          label: "Public records terminal",
          x: 78,
          y: 35,
          width: 20,
          height: 43,
          title: "Public records terminal",
          text: "The permit database is old enough to vote.",
          actionLabel: "Search Vale permits",
          actionWhen: { not: { type: "flag", key: "permitAcquired" } },
          effects: [
            { type: "setFlag", key: "permitAcquired", value: true },
            { type: "collectEvidence", id: "permit_summary" },
          ],
          resultText:
            "Permit 18-441: WEST WING ACCESSIBILITY IMPROVEMENT. The public summary omits the amendment history.",
        },
        {
          id: "clerk-window",
          label: "Lionel Price",
          x: 12,
          y: 27,
          width: 32,
          height: 38,
          title: "Lionel Price, city clerk",
          text: "He has already decided which questions you are allowed to ask.",
          actionLabel: "Question Lionel",
          dialogueId: "lionel_records",
        },
        {
          id: "records-policy",
          label: "Records policy",
          x: 43,
          y: 16,
          width: 19,
          height: 35,
          title: "Public records policy",
          text: "Requests for amendments require Form 17-C. Someone has underlined “amendments” in blue ink.",
        },
      ],
    },
    mayor_street: {
      id: "mayor_street",
      name: "Vale Residence",
      eyebrow: "West Greyhaven · 4:18 PM",
      mapX: 75,
      mapY: 57,
      description:
        "A respectable brick house on a quiet street. Nothing resembling a new west wing is visible from here.",
      sceneClass: "scene-mayor-street",
      sceneArt: "./assets/scenes/vale-street.webp",
      hotspots: [
        {
          id: "vale-house",
          label: "Mayor Vale’s house",
          x: 34,
          y: 17,
          width: 40,
          height: 54,
          title: "The Vale residence",
          text: "Old brick. Original roofline. No scaffolding, no fresh masonry, no obvious $184,600 addition.",
          actionLabel: "Photograph the west wall",
          actionWhen: {
            all: [
              { type: "hasInventory", id: "smartphone" },
              { not: { type: "hasEvidence", id: "photo_west_wall" } },
            ],
          },
          effects: [
            { type: "setFlag", key: "photographedWestWall", value: true },
            { type: "collectEvidence", id: "photo_west_wall" },
          ],
          resultText:
            "Your photograph captures uninterrupted original brickwork. Whatever the city paid for, it was not an above-ground addition.",
        },
        {
          id: "june-window",
          label: "Neighbor’s window",
          x: 4,
          y: 24,
          width: 17,
          height: 30,
          title: "Someone is watching",
          text: "The curtain moves. Whoever lives opposite the mayor has an excellent view.",
          actionLabel: "Knock on the neighbor’s door",
          dialogueId: "june_window",
        },
        {
          id: "delivery-marks",
          label: "Marks by the curb",
          x: 54,
          y: 69,
          width: 27,
          height: 18,
          title: "Heavy delivery marks",
          text: "Deep parallel grooves in the wet verge. Something heavy was unloaded here recently.",
        },
      ],
    },
    mayor_study: {
      id: "mayor_study",
      name: "Mayor Vale’s Study",
      eyebrow: "Vale Residence · 11:48 PM",
      mapX: 79,
      mapY: 52,
      description:
        "Police completed a hurried welfare check and left. Mayor Vale is missing. Her study looks orderly in the way a room does after someone has searched it.",
      sceneClass: "scene-study",
      sceneArt: "./assets/scenes/vale-study.webp",
      hotspots: [
        {
          id: "crooked-photograph",
          label: "Crooked photograph",
          x: 3,
          y: 8,
          width: 27,
          height: 44,
          title: "A deliberately crooked photograph",
          text: "The frame is crooked, but the dust shadow behind it is perfectly straight.",
          actionLabel: "Look behind the frame",
          actionWhen: { not: { type: "flag", key: "foundStudyFloorplan" } },
          effects: [
            { type: "setFlag", key: "foundStudyFloorplan", value: true },
            { type: "collectEvidence", id: "study_floorplan" },
          ],
          resultText:
            "A folded original floorplan is taped inside the frame. It shows a narrow void behind the western bookcase.",
        },
        {
          id: "dictation-recorder",
          label: "Dictation recorder",
          x: 43,
          y: 62,
          width: 18,
          height: 19,
          title: "A damaged dictation recorder",
          text: "The casing is cracked. Three fragments remain on its internal memory.",
          actionLabel: "Add it to the case file",
          actionWhen: { not: { type: "flag", key: "foundValeRecording" } },
          effects: [
            { type: "setFlag", key: "foundValeRecording", value: true },
            { type: "collectEvidence", id: "vale_damaged_recording" },
          ],
          resultText:
            "Three voice fragments survive, but their timestamps are gone. A proper recovery console may be able to rebuild the sequence.",
        },
        {
          id: "western-bookcase",
          label: "Western bookcase",
          x: 82,
          y: 14,
          width: 12,
          height: 59,
          title: "The western bookcase",
          text: "The shelves sit several inches forward of the wall shown on the original plan.",
          actionLabel: "Align the floorplan",
          actionWhen: {
            all: [
              { type: "hasEvidence", id: "study_floorplan" },
              { not: { type: "flag", key: "foundWallCavity" } },
            ],
          },
          route: "alignment",
        },
        {
          id: "missing-book",
          label: "Gap in the shelf",
          x: 73,
          y: 33,
          width: 8,
          height: 13,
          title: "A missing book",
          text: "Dust outlines the shape of a large atlas removed recently.",
        },
      ],
    },
    hidden_room: {
      id: "hidden_room",
      name: "Hidden Communications Room",
      eyebrow: "Beneath the Vale Residence",
      mapX: 82,
      mapY: 68,
      description:
        "A steel stair descends into a communications room that does not appear on any city plan.",
      sceneClass: "scene-hidden-room",
      sceneArt: "./assets/scenes/hidden-room.webp",
      hotspots: [
        {
          id: "dark-monitors",
          label: "Dark monitors",
          x: 8,
          y: 10,
          width: 34,
          height: 46,
          title: "Audio recovery console",
          text:
            "One monitor wakes when Vale’s recorder is connected. Its queue holds three voice fragments with no timestamps.",
          actionLabel: "Reconstruct the recording",
          actionWhen: { type: "hasEvidence", id: "vale_damaged_recording" },
          route: "recording",
        },
        {
          id: "guest-list-printer",
          label: "Printer tray",
          x: 76,
          y: 48,
          width: 23,
          height: 39,
          title: "One page remains",
          text: "The printer tray holds the torn header of a guest list: MERIDIAN / GREYHAVEN SESSION.",
          actionLabel: "Take the torn page",
          actionWhen: {
            not: { type: "hasEvidence", id: "meridian_guest_list_header" },
          },
          effects: [
            { type: "collectEvidence", id: "meridian_guest_list_header" },
          ],
          resultText:
            "The surviving header names a Thursday Meridian session at VALE / ROOM B. The attendee list has been torn away.",
        },
        {
          id: "cable-conduit",
          label: "Cable conduit",
          x: 0,
          y: 55,
          width: 39,
          height: 34,
          title: "Fresh cable conduit",
          text: "The conduit runs toward the street, not the house. This room was connected to something outside.",
        },
      ],
    },
  },
  officeHotspots: [
    {
      id: "evidence-board",
      label: "Evidence board",
      className: "hotspot-board",
      title: "Nothing connected. Yet.",
      text: "A clean corkboard is an optimistic thing. Soon it will hold names, receipts, photographs, and decisions you cannot take back.",
      route: "board",
    },
    {
      id: "city-map",
      label: "Greyhaven map",
      className: "hotspot-map",
      title: "Greyhaven",
      text: "City Hall. The Ledger. Mayor Vale’s house. For now, the city still fits on one wall.",
      route: "map",
    },
    {
      id: "laptop",
      label: "Laptop",
      className: "hotspot-laptop",
      title: "One unread message",
      text: "No sender. No subject. Two attachments. It arrived while you were at the Ledger.",
      route: "laptop",
    },
    {
      id: "answering-machine",
      label: "Answering machine",
      className: "hotspot-phone",
      title: "1 new message",
      text: "The red light blinks above a message from an unidentified caller.",
      action: "play-opening-message",
    },
    {
      id: "window",
      label: "Window",
      className: "hotspot-window",
      title: "Greyhaven after dark",
      text: "Rain varnishes the street. Across the road, a parked sedan keeps its lights off.",
    },
  ],
});
