export const EVIDENCE = Object.freeze({
  email_meridian: {
    id: "email_meridian",
    title: "Anonymous email",
    category: "document",
    summary: "A tip alleging Mayor Vale diverted accessibility funds.",
  },
  invoice_northstar: {
    id: "invoice_northstar",
    title: "Northstar invoice",
    category: "document",
    summary: "$184,600 billed to the municipal accessibility fund.",
  },
  permit_summary: {
    id: "permit_summary",
    title: "West-wing permit summary",
    category: "document",
    summary: "A public permit summary for an addition to Mayor Vale’s home.",
  },
  permit_amendment_note: {
    id: "permit_amendment_note",
    title: "Permit amendment note",
    category: "document",
    summary: "An amendment authorized after midnight by someone identified as E. Marsh.",
  },
  june_statement: {
    id: "june_statement",
    title: "June Bell’s statement",
    category: "recording",
    summary: "Deliveries arrived at night, but no above-ground construction followed.",
  },
});

export const INVENTORY_ITEMS = Object.freeze({
  press_credentials: { id: "press_credentials", name: "Press credentials", icon: "ID" },
  smartphone: { id: "smartphone", name: "Phone & camera", icon: "CAM" },
  recorder: { id: "recorder", name: "Audio recorder", icon: "REC" },
  notebook: { id: "notebook", name: "Reporter’s notebook", icon: "NOTE" },
});

export const DIALOGUES = Object.freeze({
  lionel_records: {
    id: "lionel_records",
    character: "Lionel Price",
    portrait: "LP",
    start: "intro",
    nodes: {
      intro: {
        id: "intro",
        speaker: "Lionel Price",
        text: "Everything available to the public is in the summary. If it is not in the summary, it is not available.",
        choices: [
          {
            id: "ask-amendment",
            text: "Who filed the amendment?",
            next: "denial",
          },
          {
            id: "show-invoice",
            text: "Then explain this Northstar invoice.",
            evidenceId: "invoice_northstar",
            requires: { type: "hasEvidence", id: "invoice_northstar" },
            next: "invoice",
          },
          { id: "leave", text: "That’s all for now.", end: true },
        ],
      },
      denial: {
        id: "denial",
        speaker: "Lionel Price",
        text: "There was no amendment. You are mistaking a system timestamp for a filing.",
        choices: [
          {
            id: "show-permit",
            text: "The public summary says ‘revision pending.’",
            evidenceId: "permit_summary",
            requires: { type: "hasEvidence", id: "permit_summary" },
            effects: [
              { type: "setFlag", key: "caughtLionelContradiction", value: true },
            ],
            next: "defensive",
          },
          { id: "ask-system", text: "Who can access the system after hours?", next: "system" },
          { id: "leave", text: "I’ll come back with the paperwork.", end: true },
        ],
      },
      invoice: {
        id: "invoice",
        speaker: "Lionel Price",
        text: "Northstar is a registered vendor. Or it was when the payment cleared. Vendor status is Finance, not Records.",
        choices: [
          { id: "press", text: "You checked after I arrived, didn’t you?", next: "defensive" },
          { id: "back", text: "Let’s start again.", next: "intro" },
        ],
      },
      system: {
        id: "system",
        speaker: "Lionel Price",
        text: "The mayor, the deputy clerk, Information Services, and anyone with an emergency authorization token.",
        choices: [
          { id: "ask-token", text: "Who used an emergency token?", next: "defensive" },
          { id: "back", text: "Back up.", next: "denial" },
        ],
      },
      defensive: {
        id: "defensive",
        speaker: "Lionel Price",
        text: "I did not authorize it. The log says E. Marsh, 12:43 AM. That is all I know—and you did not hear it from me.",
        onEnter: [
          { type: "setFlag", key: "lionelNamedMarsh", value: true },
          { type: "collectEvidence", id: "permit_amendment_note" },
        ],
        choices: [
          { id: "protect", text: "I’ll keep your name out of it.", next: "protected" },
          { id: "challenge", text: "You should have reported this.", next: "resentful" },
        ],
      },
      protected: {
        id: "protected",
        speaker: "Lionel Price",
        text: "Then write this down: the change came after the inspection, not before. That is not how permits work.",
        choices: [{ id: "finish", text: "Thank you, Lionel.", end: true }],
      },
      resentful: {
        id: "resentful",
        speaker: "Lionel Price",
        text: "To whom? The mayor? The deputy clerk? You still think the forms protect the people who file them.",
        choices: [{ id: "finish", text: "I have what I need.", end: true }],
      },
    },
  },
  june_window: {
    id: "june_window",
    character: "June Bell",
    portrait: "JB",
    start: "intro",
    nodes: {
      intro: {
        id: "intro",
        speaker: "June Bell",
        text: "If you’re selling something, I’m eighty years old and already own too much of everything.",
        choices: [
          { id: "press", text: "I’m with the Greyhaven Ledger.", next: "journalist" },
          { id: "direct", text: "Did you see construction at Mayor Vale’s house?", next: "construction" },
          { id: "leave", text: "Sorry to bother you.", end: true },
        ],
      },
      journalist: {
        id: "journalist",
        speaker: "June Bell",
        text: "A journalist? The last one who came here wanted a photograph of Evelyn planting tulips.",
        choices: [
          { id: "ask-delivery", text: "I’m interested in the nighttime deliveries.", next: "construction" },
          { id: "leave", text: "I may come back.", end: true },
        ],
      },
      construction: {
        id: "construction",
        speaker: "June Bell",
        text: "Three trucks after midnight. Men carried equipment through the side gate. But nobody built a west wing. I would have noticed a room appearing.",
        onEnter: [
          { type: "setFlag", key: "juneSawDeliveries", value: true },
          { type: "collectEvidence", id: "june_statement" },
        ],
        choices: [
          { id: "ask-sound", text: "What did you hear?", next: "sound" },
          { id: "ask-men", text: "Could you identify the workers?", next: "workers" },
        ],
      },
      sound: {
        id: "sound",
        speaker: "June Bell",
        text: "A low vibration. Not hammering—more like drilling, except it came up through the floorboards.",
        choices: [{ id: "finish", text: "May I quote you?", end: true }],
      },
      workers: {
        id: "workers",
        speaker: "June Bell",
        text: "No uniforms. One van had a compass-star logo. I sketched it because I did not trust my memory.",
        choices: [{ id: "finish", text: "I’d like to see that sketch later.", end: true }],
      },
    },
  },
});

export const GAME_CONTENT = Object.freeze({
  title: "The Benefactors",
  subtitle: "Every good lie leaves paperwork.",
  chapter: "Prologue · The Renovation",
  locations: {
    home_office: {
      id: "home_office",
      name: "Home Office",
      mapX: 51,
      mapY: 62,
      description: "Your apartment and the center of the investigation.",
    },
    ledger_newsroom: {
      id: "ledger_newsroom",
      name: "The Greyhaven Ledger",
      eyebrow: "Tomorrow's news, yesterday's computers",
      mapX: 34,
      mapY: 40,
      description:
        "The night desk glows beneath tired fluorescent lights. Mara is waiting with an assignment that should be simple.",
      sceneClass: "scene-newsroom",
      hotspots: [
        {
          id: "mara-desk",
          label: "Mara Venn",
          x: 67,
          y: 27,
          width: 18,
          height: 47,
          title: "Mara’s desk",
          text: "Your editor has gone home. Her coffee has not.",
        },
        {
          id: "deadline-clock",
          label: "Deadline clock",
          x: 78,
          y: 8,
          width: 12,
          height: 13,
          title: "9:32 PM",
          text: "The clock is four minutes fast. Mara calls that optimism.",
        },
        {
          id: "archive-boxes",
          label: "Archive boxes",
          x: 5,
          y: 51,
          width: 27,
          height: 31,
          title: "Municipal archive",
          text: "Last year’s council minutes. Useful if the city ever starts repeating itself.",
        },
      ],
    },
    city_hall: {
      id: "city_hall",
      name: "Greyhaven City Hall",
      eyebrow: "Records Division · 10:06 AM",
      mapX: 57,
      mapY: 35,
      description:
        "Marble, fluorescent light, and the institutional confidence that no one reads the forms.",
      sceneClass: "scene-city-hall",
      hotspots: [
        {
          id: "records-terminal",
          label: "Public records terminal",
          x: 57,
          y: 36,
          width: 20,
          height: 30,
          title: "Public records terminal",
          text: "The permit database is old enough to vote.",
          actionLabel: "Search Vale permits",
          actionWhen: { not: { type: "flag", key: "permitAcquired" } },
          effects: [
            { type: "setFlag", key: "permitAcquired", value: true },
            { type: "collectEvidence", id: "permit_summary" },
          ],
          resultText:
            "Permit 18-441: WEST WING ACCESSIBILITY IMPROVEMENT. The public summary omits the amendment history.",
        },
        {
          id: "clerk-window",
          label: "Lionel Price",
          x: 12,
          y: 27,
          width: 32,
          height: 38,
          title: "Lionel Price, city clerk",
          text: "He has already decided which questions you are allowed to ask.",
          actionLabel: "Question Lionel",
          dialogueId: "lionel_records",
        },
        {
          id: "records-policy",
          label: "Records policy",
          x: 40,
          y: 11,
          width: 12,
          height: 20,
          title: "Public records policy",
          text: "Requests for amendments require Form 17-C. Someone has underlined “amendments” in blue ink.",
        },
      ],
    },
    mayor_street: {
      id: "mayor_street",
      name: "Vale Residence",
      eyebrow: "West Greyhaven · 4:18 PM",
      mapX: 75,
      mapY: 57,
      description:
        "A respectable brick house on a quiet street. Nothing resembling a new west wing is visible from here.",
      sceneClass: "scene-mayor-street",
      hotspots: [
        {
          id: "vale-house",
          label: "Mayor Vale’s house",
          x: 34,
          y: 17,
          width: 40,
          height: 54,
          title: "The Vale residence",
          text: "Old brick. Original roofline. No scaffolding, no fresh masonry, no obvious $184,600 addition.",
        },
        {
          id: "june-window",
          label: "Neighbor’s window",
          x: 4,
          y: 24,
          width: 17,
          height: 30,
          title: "Someone is watching",
          text: "The curtain moves. Whoever lives opposite the mayor has an excellent view.",
          actionLabel: "Knock on the neighbor’s door",
          dialogueId: "june_window",
        },
        {
          id: "delivery-marks",
          label: "Marks by the curb",
          x: 54,
          y: 69,
          width: 27,
          height: 18,
          title: "Heavy delivery marks",
          text: "Deep parallel grooves in the wet verge. Something heavy was unloaded here recently.",
        },
      ],
    },
    mayor_study: {
      id: "mayor_study",
      name: "Mayor Vale’s Study",
      eyebrow: "Locked location",
      mapX: 79,
      mapY: 52,
      description: "Not yet accessible.",
      sceneClass: "scene-study",
      hotspots: [],
    },
    hidden_room: {
      id: "hidden_room",
      name: "Hidden Communications Room",
      eyebrow: "Unknown location",
      mapX: 82,
      mapY: 51,
      description: "Not yet accessible.",
      sceneClass: "scene-hidden-room",
      hotspots: [],
    },
  },
  officeHotspots: [
    {
      id: "evidence-board",
      label: "Evidence board",
      className: "hotspot-board",
      title: "Nothing connected. Yet.",
      text: "A clean corkboard is an optimistic thing. Soon it will hold names, receipts, photographs, and decisions you cannot take back.",
    },
    {
      id: "city-map",
      label: "Greyhaven map",
      className: "hotspot-map",
      title: "Greyhaven",
      text: "City Hall. The Ledger. Mayor Vale’s house. For now, the city still fits on one wall.",
      route: "map",
    },
    {
      id: "laptop",
      label: "Laptop",
      className: "hotspot-laptop",
      title: "One unread message",
      text: "No sender. No subject. Two attachments. It arrived while you were at the Ledger.",
      route: "laptop",
    },
    {
      id: "answering-machine",
      label: "Answering machine",
      className: "hotspot-phone",
      title: "No new messages",
      text: "The red light is dark. Silence feels ordinary tonight.",
    },
    {
      id: "window",
      label: "Window",
      className: "hotspot-window",
      title: "Greyhaven after dark",
      text: "Rain varnishes the street. Across the road, a parked sedan keeps its lights off.",
    },
  ],
});
