export const PRESSURE_EVENTS = Object.freeze([
  { id: "parked-sedan", title: "A car starts keeping office hours", text: "The dark sedan across from the apartment appears after the anonymous files are opened.", heat: 5, deadline: "The first deadline is still tonight.", eligibleWhen: { type: "flag", key: "openedAnonymousEmail" } },
  { id: "vale-missing", title: "The story loses its safest witness", text: "Vale's disappearance turns a paperwork story into a live threat assessment.", heat: 7, deadline: "The study will not remain unsecured for long.", eligibleWhen: { type: "flag", key: "mayorMissing" } },
  { id: "room-b-notice", title: "Meridian notices the questions", text: "Room B names a reporter matching your description and orders Harcourt moved.", heat: 9, deadline: "Reach Mina before the transfer team does.", eligibleWhen: { type: "flag", key: "recordedRoomBConversation" } },
  { id: "archive-purge", title: "The paper trail starts burning", text: "Wren's destruction order advances while the municipal archive quietly closes aisles.", heat: 8, deadline: "Register 09 is in the destruction queue.", eligibleWhen: { type: "flag", key: "foundArchiveDestructionOrder" } },
  { id: "bellwether-containment", title: "A community becomes a containment zone", text: "Meridian security begins photographing organizers at the Bellwether relief station.", heat: 7, deadline: "The duplicate sample is the next target.", eligibleWhen: { type: "flag", key: "provedBellwetherResponsePreplanned" } },
  { id: "crownline-trace", title: "Crownline scores the investigator", text: "A failed login probe hits the Ledger's source desk seconds after the governance model is copied.", heat: 10, deadline: "Redoubt's protected flight window is already open.", eligibleWhen: { type: "flag", key: "provedCrownlineGovernanceModel" } },
  { id: "redoubt-tail", title: "The tail stops pretending", text: "A black vehicle follows the service road toward Blackwater Point, then kills its lights.", heat: 8, deadline: "The Orpheus launch leaves on the tide.", eligibleWhen: { type: "flag", key: "provedRedoubtEvacuation" } },
  { id: "orpheus-breach", title: "Missing on an island that does not exist", text: "Your borrowed credential has minutes before the Orpheus security wall marks it revoked.", heat: 12, deadline: "Reach Level 07 before the next badge sweep.", eligibleWhen: { type: "flag", key: "provedOrpheusCommandCenter" } },
  { id: "first-circle-clock", title: "Port Prosper: forty-eight hours", text: "The First Circle vote starts a real operational clock. How you use the evidence now will have consequences.", heat: 12, deadline: "The planned conversion begins in forty-eight hours.", eligibleWhen: { type: "flag", key: "provedBenefactorsSelectCrises" } },
  { id: "aster-countdown", title: "The local trigger cell is active", text: "Aster House keeps the attack live even after the First Circle is exposed.", heat: 10, deadline: "Relay Seven opens at 02:10.", eligibleWhen: { type: "flag", key: "identifiedAsterHouse" } },
  { id: "newsroom-compromised", title: "The newsroom cipher was copied", text: "The failed Port Prosper attack reveals that Meridian cloned a protected Ledger source channel.", heat: 12, deadline: "Vesper's courier locker opens at 05:30.", eligibleWhen: { type: "flag", key: "foundNewsroomCipherClone" } },
]);

export const COUNTERMEASURES = Object.freeze([
  { id: "mirror-files", title: "Mirror the case file", text: "Split encrypted copies between the Ledger, a civic archive, and an offline drive.", heat: -6, availableWhen: { type: "flag", key: "downloadedAttachments" } },
  { id: "check-tail", title: "Run a surveillance check", text: "Change routes, photograph the sedan, and force the tail to reveal its hand.", heat: -7, availableWhen: { type: "flag", key: "mayorMissing" } },
  { id: "warn-sources", title: "Warn every active source", text: "Move vulnerable contacts and suspend routine check-ins. Their exposure falls; yours rises.", heat: 4, sourceRisk: -1, availableWhen: { type: "flag", key: "uncoveredContractorNetwork" } },
  { id: "false-itinerary", title: "Seed a false itinerary", text: "Let Redoubt waste a team watching the wrong coastal road.", heat: -10, availableWhen: { type: "flag", key: "provedRedoubtEvacuation" } },
  { id: "rotate-cipher", title: "Rotate the newsroom cipher", text: "Burn the compromised source channel and move Mara's copies to a clean key.", heat: -9, sourceRisk: -1, availableWhen: { type: "flag", key: "foundNewsroomCipherClone" } },
]);
